[package]
name = "tamara"
version = "0.1.0"
authors = ["Alexander Ortíz <vtacius@gmail.com>"]
license = "MIT"
description = "Herramienta de monitoreo ICMP"
repository = "https://github.com/vtacius/tamara"
edition = "2018"

[dependencies]
socket2 = { version = "0.4", features = ["all"] }
thiserror = "1.0"
rand = "0.8"
log = "0.4.17"
libc = "0.2.132"
